version: '3.9'

services:
  web:
    command: "-f /dev/null"
    container_name: "twitch-server"
    entrypoint: /usr/bin/tail
    tty: true
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/twitch